services:
  # nginx
  web:
    image: nginx:latest
    ports: 
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html

  # php
  app:
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor

  # mysql
  db:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "4306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: docker-php

volumes:
  mysqldata:
