name: 🚀 Deploy website on push

on:
  push:
    branches:
      - iss-20

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📦 Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          coverage: none

      - name: 🔑 Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-${{ runner.os }}-

      - name: 🧑‍💻 Install dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: 🕵️ Verify installed dependencies
        run: composer show --direct

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER_ADDRESS }}
          username: ${{ secrets.FTP_SERVER_USER }}
          password: ${{ secrets.FTP_SERVER_PASS }}
          exclude: |
            **/.git*
            **/.git*/**
            **/.github*
            **/.github*/**
            **/docker*
            **/docker*/**
            **/documentation*
            **/documentation*/**
            **/.gitignore
            **/cli.php
            **/docker-compose.yaml
            **/database_credentials.php
            **/README.MD
