name: Windows Command Line Workflow

on:
  push:
    branches:
      - ci_cd
  pull_request:
    branches:
      - ci_cd

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create FTP commands file
        run: |
          echo open %FTP_SERVER_ADDRESS% > ftp_commands.txt
          echo %FTP_SERVER_USER% >> ftp_commands.txt
          echo %FTP_SERVER_PASS% >> ftp_commands.txt
          echo binary >> ftp_commands.txt
          echo prompt >> ftp_commands.txt
          echo mput * >> ftp_commands.txt
          echo bye >> ftp_commands.txt

      - name: Run FTP commands
        env:
          FTP_SERVER_ADDRESS: ${{ secrets.FTP_SERVER_ADDRESS }}
          FTP_SERVER_USER: ${{ secrets.FTP_SERVER_USER }}
          FTP_SERVER_PASS: ${{ secrets.FTP_SERVER_PASS }}
        run: |
          ftp -s:ftp_commands.txt