name: 🚀 Deploy website on push

on:
  push:
    branches:
      - ci_cd

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
    
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER_ADDRESS }}
          username: ${{ secrets.FTP_SERVER_USER }}
          password: ${{ secrets.FTP_SERVER_PASS }}
