name: FTP Upload Workflow

on:
  push:
    branches:
      - ci_cd
  pull_request:
    branches:
      - ci_cd

jobs:
  upload:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run PowerShell script for FTP upload
        env:
          FTP_SERVER_ADDRESS: ${{ secrets.FTP_SERVER_ADDRESS }}
          FTP_SERVER_USER: ${{ secrets.FTP_SERVER_USER }}
          FTP_SERVER_PASS: ${{ secrets.FTP_SERVER_PASS }}
        run: |
         .\deploy.ps1 -$ftpServer "%FTP_SERVER ADDRESS%" -ftpUser "%FTP_SERVER_USER%" -$ftpPass "%FTP_SERVER_PASS%"
