name: Windows Command Line Workflow

on:
  push:
    branches:
      - ci_cd
  pull_request:
    branches:
      - ci_cd

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Navigate to workspace and run commands
        shell: pwsh
        run: |
          Write-Output "Navigating to the GITHUB_WORKSPACE directory..."
          Set-Location -Path $env:GITHUB_WORKSPACE
          Write-Output "Current directory after change:"
          Get-Location
          Write-Output "Running commands in the workspace directory:"
          Get-ChildItem
