name: Windows Command Line Workflow

on:
  push:
    branches:
      - ci_cd
  pull_request:
    branches:
      - ci_cd

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Navigate to workspace and run commands
        run: |
          echo "The list of files in this folder:"
          dir
