name: FTP Upload Workflow

on:
  push:
    branches:
      - ci_cd
  pull_request:
    branches:
      - ci_cd

jobs:
  upload:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run PowerShell script for FTP upload
        env:
          FTP_SERVER_ADDRESS: ${{ secrets.FTP_SERVER_ADDRESS }}
          FTP_SERVER_USER: ${{ secrets.FTP_SERVER_USER }}
          FTP_SERVER_PASS: ${{ secrets.FTP_SERVER_PASS }}
        run: |
          pwsh -Command '
          $ftpServer = "%FTP_SERVER_ADDRESS%"
          $ftpUser = "%$FTP_SERVER_USER%"
          $ftpPass = "%$FTP_SERVER_PASS%"

          $files = Get-ChildItem -Path "." -File
          foreach ($file in $files) {
              $ftpUri = "ftp://"+$ftpServer+"/"+$file.Name
              $ftp = [System.Net.FtpWebRequest]::Create($ftpUri)
              $ftp.Method = [System.Net.WebRequestMethods+Ftp]::UploadFile
              $ftp.Credentials = New-Object System.Net.NetworkCredential($ftpUser, $ftpPass)

              $fileStream = [System.IO.File]::OpenRead($file.FullName)
              $requestStream = $ftp.GetRequestStream()
              $fileStream.CopyTo($requestStream)
              $requestStream.Close()
              $fileStream.Close()
          }
          '
