name: Convert Markdown to PDF

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  convert-md-to-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v2

    - name: Clone GitHub Wiki repository
      run: |
        git clone https://github.com/ZsakaiBalint/portfolio-website.wiki.git wiki-repo

    - name: Install Pandoc and LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended

    - name: Convert Markdown to PDF
      run: |
        mkdir -p docs
        cd wiki-repo
        pandoc *.md --pdf-engine=xelatex -o ../docs/output.pdf

    - name: Commit and push PDF to main repository
      run: |
        cd ..
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add docs/output.pdf
        git commit -m "Add generated PDF file"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
